version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor: 
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "FbcManagement/FbcManagement.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "FbcManagement/FbcManagement.csproj" }}
      - run:
          name: "Run application tests"
          command: dotnet.exe test -v -n --results-directory:test_coverage --collect:"Code Coverage"
      #- run:
      #    name: "Print Working Directory"
      #    command: pwd
      - run:
          store_artifacts:
            path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Build step"
          command: dotnet.exe build --configuration Release
workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
     # - run:
      #    name: "Test the executable"
       #   command: .\bin\Release\netcoreapp3.0\win10-x64\publish\circleci-demo-windows.exe
     # - store_artifacts:
     #     path: .\bin\Release\netcoreapp3.0\win10-x64\publish\circleci-demo-windows.exe